import { mkdir, readFile, writeFile } from "node:fs/promises";
import type { PatientPortalPlanV1 } from "../modules/nutriflow/contracts/v1/patient-portal.ts";
import { buildClinicalEvolutionReportPdf, buildPlanReportPdf } from "../modules/nutriflow/reports/professional-pdf.ts";

const output = new URL("../output/pdf/", import.meta.url);
await mkdir(output, { recursive: true });
const logoBytes = new Uint8Array(await readFile(new URL("../public/logo-ludgero.png", import.meta.url)));
const gram = Object.freeze({ publicId: "unit_g", code: "g", label: "g" });
const unit = Object.freeze({ publicId: "unit_un", code: "un", label: "unidade" });
const plan: PatientPortalPlanV1 = Object.freeze({ publicationPublicId: "pub_example", planPublicId: "plan_example", planVersionPublicId: "version_example", title: "Estratégia alimentar individualizada", versionNumber: 4, contentHash: "example", publishedAt: "2026-08-08T12:00:00.000Z", notes: "Objetivo: redução de gordura corporal com preservação de massa muscular.", patientNotes: Object.freeze(["Mantenha boa hidratação ao longo do dia.", "Organize as refeições conforme os horários da sua rotina."]), macros: Object.freeze({ energyKcal: 2180, protein: 165, carbohydrate: 225, fat: 68, fiber: 31 }), days: Object.freeze([{ publicId: "strategy", label: "Estratégia para dias de treino", dayIndex: null, meals: Object.freeze([
  { publicId: "breakfast", title: "Café da manhã", scheduledTime: "07:30", instructions: "Café e chá podem ser consumidos sem açúcar.", nutritionComplete: true, macros: Object.freeze({ energyKcal: 440, protein: 28, carbohydrate: 52, fat: 14, fiber: 7 }), items: Object.freeze([]), substitutions: Object.freeze([]), options: Object.freeze([{ publicId: "breakfast_1", label: "Opção 1", sortOrder: 0, items: Object.freeze([{ publicId: "bread", kind: "food", displayName: "Pão integral", quantityMilli: 2_000, unit, preparation: "tostado", notes: null, recipe: null }, { publicId: "eggs", kind: "food", displayName: "Ovos", quantityMilli: 2_000, unit, preparation: "mexidos com pouco azeite", notes: null, recipe: null }, { publicId: "papaya", kind: "food", displayName: "Mamão", quantityMilli: 150_000, unit: gram, preparation: null, notes: null, recipe: null }]), substitutions: Object.freeze([{ publicId: "fruit_swap", mealItemPublicId: "papaya", title: "Trocar a fruta", notes: null, options: Object.freeze([{ publicId: "banana", displayName: "Banana", quantityMilli: 100_000, unit: gram, notes: null }, { publicId: "apple", displayName: "Maçã", quantityMilli: 130_000, unit: gram, notes: null }]) }]) }]) },
  { publicId: "lunch", title: "Almoço", scheduledTime: "12:30", instructions: "Tempere a salada com limão, ervas e azeite na quantidade orientada.", nutritionComplete: true, macros: Object.freeze({ energyKcal: 690, protein: 52, carbohydrate: 74, fat: 20, fiber: 11 }), items: Object.freeze([]), substitutions: Object.freeze([]), options: Object.freeze([{ publicId: "lunch_1", label: "Opção 1", sortOrder: 0, items: Object.freeze([{ publicId: "rice", kind: "food", displayName: "Arroz branco cozido", quantityMilli: 120_000, unit: gram, preparation: null, notes: null, recipe: null }, { publicId: "beans", kind: "food", displayName: "Feijão carioca", quantityMilli: 100_000, unit: gram, preparation: null, notes: null, recipe: null }, { publicId: "chicken", kind: "food", displayName: "Peito de frango", quantityMilli: 150_000, unit: gram, preparation: "grelhado", notes: null, recipe: null }, { publicId: "salad", kind: "manual", displayName: "Salada variada", quantityMilli: 1_000, unit, preparation: "à vontade", notes: null, recipe: null }]), substitutions: Object.freeze([{ publicId: "protein_swap", mealItemPublicId: "chicken", title: "Trocar a proteína", notes: null, options: Object.freeze([{ publicId: "tilapia", displayName: "Tilápia grelhada", quantityMilli: 170_000, unit: gram, notes: null }, { publicId: "beef", displayName: "Patinho grelhado", quantityMilli: 140_000, unit: gram, notes: null }]) }]) }]) },
]) }]) });

const initial = Object.freeze({ publicId: "assess_initial", capturedAt: "2026-06-08T12:00:00.000Z", protocolCode: "pollock_7", protocolVersion: "1.0.0", weightKg: 86.4, heightCm: 172, bmi: 29.2, bodyFatPct: 24.8, fatMassKg: 21.4, leanMassKg: 65.0, circumferencesCm: Object.freeze({ arm: 37, waist: 92, abdomen: 96, hip: 103, thigh: 61 }) });
const current = Object.freeze({ publicId: "assess_current", capturedAt: "2026-08-08T12:00:00.000Z", protocolCode: "pollock_7", protocolVersion: "1.0.0", weightKg: 82.1, heightCm: 172, bmi: 27.8, bodyFatPct: 20.6, fatMassKg: 16.9, leanMassKg: 65.2, circumferencesCm: Object.freeze({ arm: 37.5, waist: 87, abdomen: 90, hip: 100, thigh: 60 }) });

await writeFile(new URL("nutriflow-plano-alimentar-exemplo.pdf", output), await buildPlanReportPdf({ patientName: "Paciente Exemplo", nutritionistName: "Ludgero Sangaletti", nutritionistRegistration: "CRN-8 11719", validFrom: "2026-08-08", validUntil: "2026-10-08", plan, logoBytes }));
await writeFile(new URL("nutriflow-evolucao-clinica-exemplo.pdf", output), await buildClinicalEvolutionReportPdf({ patientName: "Paciente Exemplo", nutritionistName: "Ludgero Sangaletti", nutritionistRegistration: "CRN-8 11719", initial, current, trajectory: [initial, current], logoBytes }));
